# Generated by Django 3.0.7 on 2020-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('afce', models.CharField(max_length=15)),
                ('afce_score', models.IntegerField(max_length=5)),
                ('afcn', models.CharField(max_length=15)),
                ('afcn_score', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=10)),
                ('score', models.IntegerField(max_length=5)),
            ],
        ),
    ]
