# Generated by Django 3.0.7 on 2020-06-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0002_auto_20200624_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='afce_score',
        ),
        migrations.RemoveField(
            model_name='person',
            name='afcn_score',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='score',
        ),
    ]
