# Generated by Django 3.0.7 on 2020-06-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0004_auto_20200624_1809'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('afce', 'afcn'), name='unique_picks'),
        ),
    ]
