# Generated by Django 3.0.7 on 2020-07-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0006_auto_20200625_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='afce_score',
            new_name='afcescore',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='afcn_score',
            new_name='afcnscore',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='score',
            new_name='points',
        ),
        migrations.AddField(
            model_name='person',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
