# Generated by Django 3.0.7 on 2020-07-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0007_auto_20200701_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='picks',
        ),
    ]
