# Generated by Django 3.0.7 on 2020-07-02 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0008_auto_20200702_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(blank=True, default=0, null=True)),
                ('away', models.CharField(max_length=20)),
                ('awayscore', models.IntegerField(blank=True, default=0, null=True)),
                ('home', models.CharField(max_length=20)),
                ('homescore', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'games',
            },
        ),
        migrations.AlterModelOptions(
            name='picks',
            options={'verbose_name_plural': 'picks'},
        ),
        migrations.RemoveConstraint(
            model_name='picks',
            name='unique_picks',
        ),
        migrations.AddField(
            model_name='picks',
            name='afcs',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picks',
            name='afcsscore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='picks',
            name='afcw',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picks',
            name='afcwscore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='picks',
            name='nfce',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picks',
            name='nfcescore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='picks',
            name='nfcn',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picks',
            name='nfcnscore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='picks',
            name='nfcs',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picks',
            name='nfcsscore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='picks',
            name='nfcw',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picks',
            name='nfcwscore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='week1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week10',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week11',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week12',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week13',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week14',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week15',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week16',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week17',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week7',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week8',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='week9',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='picks',
            name='afce',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='picks',
            name='afcn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='picks',
            name='email',
            field=models.EmailField(max_length=75),
        ),
        migrations.AlterField(
            model_name='picks',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teams',
            name='division',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='picks',
            constraint=models.UniqueConstraint(fields=('afce', 'afcn', 'afcs', 'afcw', 'nfce', 'nfcn', 'nfcs', 'nfcw'), name='unique_picks'),
        ),
    ]
