# Generated by Django 3.0.7 on 2020-07-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0009_auto_20200702_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picks',
            name='afce',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='picks',
            name='afcn',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='picks',
            name='afcs',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='picks',
            name='afcw',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='picks',
            name='nfce',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='picks',
            name='nfcn',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='picks',
            name='nfcs',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='picks',
            name='nfcw',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
