# Generated by Django 3.0.7 on 2020-07-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0010_auto_20200702_2039'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teams',
            constraint=models.UniqueConstraint(fields=('team', 'division', 'status'), name='unique_teams'),
        ),
    ]
