# Generated by Django 3.0.7 on 2020-07-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0011_auto_20200703_1912'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='games',
            constraint=models.UniqueConstraint(fields=('week', 'away'), name='unique_away'),
        ),
        migrations.AddConstraint(
            model_name='games',
            constraint=models.UniqueConstraint(fields=('week', 'home'), name='unique_home'),
        ),
    ]
