# Generated by Django 3.0.7 on 2020-07-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0013_auto_20200708_1239'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teams',
            name='unique_teams',
        ),
        migrations.AddConstraint(
            model_name='teams',
            constraint=models.UniqueConstraint(fields=('team',), name='unique_teams'),
        ),
    ]
